CREATE DATABASE IF NOT EXISTS handymantools;
USE handymantools;

CREATE TABLE CUSTOMERS ( 
Email VARCHAR(40) NOT NULL, 
Password varchar(20) NOT NULL,
FirstName varchar(25) NOT NULL,
LastName varchar(40) NOT NULL,
CountryCodeW VARCHAR(5) NOT NULL, 
LocalNumW VARCHAR(10) NOT NULL, 
CountryCodeH VARCHAR(5)NOT NULL, 
LocalNumH VARCHAR(10) NOT NULL, 
Address VARCHAR(100)NOT NULL, 
PRIMARY KEY (Email)
);

CREATE TABLE CLERKS(
Login VARCHAR(40) NOT NULL, 
Password varchar(20) NOT NULL,
FirstName varchar(25) NOT NULL,
LastName varchar(40) NOT NULL,
PRIMARY KEY (Login)
);

CREATE TABLE RESERVATIONS(
ResID VARCHAR(10) NOT NULL UNIQUE, 
ClerkPickUp VARCHAR(40) DEFAULT NULL, 
ClerkDropOff VARCHAR(40) DEFAULT NULL, 
CuEmail VARCHAR(40) DEFAULT NULL, 
ResStartDate DATE NOT NULL, 
ResEndDate DATE NOT NULL CHECK(ResStartDate < ResEndDate AND ResStartDate >= CURRENT_DATE()),
CreditCardNo VARCHAR(16) DEFAULT NULL, 
ExpDate DATE DEFAULT NULL, 
PRIMARY KEY (ResID), 
FOREIGN KEY (ClerkDropOff) REFERENCES CLERKS (Login) ON DELETE SET NULL ON UPDATE CASCADE , 
FOREIGN KEY (ClerkPickUp) REFERENCES CLERKS (Login) ON DELETE SET NULL ON UPDATE CASCADE, 
FOREIGN KEY (CuEmail) REFERENCES CUSTOMERS (Email) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE TOOLS(
ToolID VARCHAR(5) NOT NULL UNIQUE, 
ClerkSellTool VARCHAR(40) DEFAULT NULL, 
AbbrDes VARCHAR(40) NOT NULL, 
FullDes VARCHAR(200), 
PurchasePrice DECIMAL(10,2) CHECK (PurchasePrice > 0), 
RentPrice DECIMAL(10,2) CHECK (RentPrice > 0), 
Deposit DECIMAL(10,2) CHECK (Deposit >= 0),
ToolType VARCHAR(20) NOT NULL,
PRIMARY KEY (ToolID), 
FOREIGN KEY (ClerkSellTool) REFERENCES CLERKS (Login) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY (ClerkAddTool) REFERENCES CLERKS (Login) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE SERVICE_REQUEST (
Clerk VARCHAR(40) NOT NULL, 
TID VARCHAR (5) NOT NULL, 
StartDate DATE NOT NULL CHECK (StartDate <= EndDate AND StartDate >= CURDATE()), 
EndDate DATE NOT NULL, 
EstCost DECIMAL(10,2) CHECK (EstCost >= 0), 
PRIMARY KEY (TID, StartDate), 
FOREIGN KEY (Clerk) REFERENCES CLERKS (Login) ON DELETE CASCADE ON UPDATE CASCADE, 
FOREIGN KEY (TID) REFERENCES TOOLS (ToolID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONTAIN (
RID VARCHAR(10) NOT NULL, 
TID VARCHAR(5) NOT NULL, 
PRIMARY KEY (RID, TID), 
FOREIGN KEY (RID) REFERENCES RESERVATIONS (ResID) ON DELETE CASCADE ON UPDATE CASCADE, 
FOREIGN KEY (TID) REFERENCES TOOLS (ToolID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE  POWER_TOOLS_ACCES (
ToolID VARCHAR(10) NOT NULL, 
Accessories VARCHAR(255) NOT NULL, 
PRIMARY KEY (ToolID, Accessories), 
FOREIGN KEY (ToolID) REFERENCES TOOLS (ToolID) ON DELETE CASCADE ON UPDATE CASCADE
);






